name: Backport
on:
  pull_request_target:
    types:
      - closed
      #- labeled Commenting this out for now, I think we only want to backport when the PR is closed.

jobs:
  backport:
    name: Backport
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    # Only react to merged PRs for security reasons.
    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target.
    if: |
      github.event.pull_request.merged == true && (
        github.event.action == 'closed' || (
          github.event.action == 'labeled' && 
          contains(github.event.pull_request.labels.*.name, 'backport')
        )
      )
     
    steps:
      - uses: tibdex/backport@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backport_branch: 'backport-branch' # Replace with your target branch name
          pr_number: ${{ github.event.pull_request.number }}
          labels: |
            cherry-pick
          commit_message_suffix: ' Backporting to supported releases: (backported)'