name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backport:
    name: Backport
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    # Only react to merged PRs for security reasons.
    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target.
    # contains(github.event.pull_request.labels.*.name, 'backport')
    if: |
      github.event.pull_request.merged == true && (
        github.event.action == 'closed' || (
          github.event.action == 'labeled' && 
          contains(github.event.label.name, 'backport')
        )
      )
  
    steps:
      - uses: tibdex/backport@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          label_pattern: '^release-(.+)$'  # Regex to match the backport branch label, "release-XYZ"
          title_template: '[BACKPORT {{base}}] {{title}}'
          head_template: 'This is an automated backport of PR {{number}} to branch {{base}}'
